/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bicycle;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah Fawwaz Q
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
        Frame(this);
        isi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("RETURN");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("ID RETURN:");

        jTextField12.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ID TRANSACTION:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("RETURN DATE:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("CONDITION:");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "Bad" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("MULCT:");

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("SEARCH:");

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("SAVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("UPDATE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton7)
                                        .addGap(68, 68, 68)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel12))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String idr, idt, idb, rd, mul, con;
    public void DataReturn()
    {
        idr = jTextField12.getText();
        idt = jTextField18.getText();
        SimpleDateFormat sdf;
        sdf = new SimpleDateFormat("dd-MM-yyyy");
        rd = sdf.format(jDateChooser2.getDate());
        mul = jTextField14.getText();
        con = jComboBox5.getSelectedItem().toString();
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DataReturn();
        if (idt.length() > 0 && mul.length() > 0)
        {
            try
            {
                sql_connect.Koneksi();
                String idp = jTextField12.getText();
                String sql = "SELECT * FROM pengembalian WHERE id_pengembalian like '"+idp+"' or id_transaksi like '"+jTextField18.getText()+"'";
                PreparedStatement gidc = sql_connect.sqlConnect.prepareStatement(sql);
                ResultSet rs = gidc.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Data Return has been found");
                    this.hide();
                }
                else
                {
                    String idtr = jTextField18.getText();
                    String ccus = "SELECT * FROM transaksi WHERE id_transaksi like '"+idtr+"'";
                    PreparedStatement ccu = sql_connect.sqlConnect.prepareStatement(ccus);
                    ResultSet hcu = ccu.executeQuery();
                    if(hcu.next())
                    {
                        try
                        {
                            String save = "insert into pengembalian values ('"+idr+"', '"+idt+"', '"+rd+"', '"+mul+"', '"+con+"')";
                            PreparedStatement sv = sql_connect.sqlConnect.prepareStatement(save);
                            sv.executeUpdate();

                            String update = "update sepeda set status_sepeda='Available' where id_sepeda='"+hcu.getString("id_sepeda")+"'";
                            PreparedStatement ud = sql_connect.sqlConnect.prepareStatement(update);
                            ud.executeUpdate();

                            JOptionPane.showMessageDialog(rootPane, "Data has been save");
                            this.hide();
                        }
                        catch (Exception a)
                        {
                            JOptionPane.showMessageDialog(rootPane, a);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Please enter valid ID Transaction");
                    }
                }
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null, ex);
                this.hide();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter data");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DataReturn();
        try
        {
            sql_connect.Koneksi();
            String idp = jTextField12.getText();
            String sql = "SELECT * FROM pengembalian WHERE id_pengembalian like '"+idp+"' or id_transaksi like '"+jTextField18.getText()+"'";
            PreparedStatement gidc = sql_connect.sqlConnect.prepareStatement(sql);
            ResultSet rs = gidc.executeQuery();
            if(rs.next())
            {
                if (idt.length() > 0 && mul.length() > 0)
                {
                    String idtr = jTextField18.getText();
                    String ccus = "SELECT * FROM transaksi WHERE id_transaksi like '"+idtr+"'";
                    PreparedStatement ccu = sql_connect.sqlConnect.prepareStatement(ccus);
                    ResultSet hcu = ccu.executeQuery();
                    if(hcu.next())
                    {
                        try
                        {
                            String save = "update pengembalian set id_transaksi='"+idt+"', tgl_pengembalian='"+rd+"', denda='"+mul+"', kondisi_sepeda='"+con+"' where id_pengembalian='"+idr+"'";
                            PreparedStatement sv = sql_connect.sqlConnect.prepareStatement(save);
                            sv.executeUpdate();

                            String update = "update sepeda set status_sepeda='Available' where id_sepeda='"+hcu.getString("id_sepeda")+"'";
                            PreparedStatement ud = sql_connect.sqlConnect.prepareStatement(update);
                            ud.executeUpdate();

                            JOptionPane.showMessageDialog(rootPane, "Data has been update");
                            this.hide();
                        }
                        catch (Exception a)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Data failed to update");
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Please enter valid ID Transaction");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Please enter data");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Return not found");
                jTextField1.requestFocus();
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            this.hide();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        DataReturn();
        try
        {
            sql_connect.Koneksi();
            String idp = jTextField12.getText();
            String sql = "SELECT * FROM pengembalian WHERE id_pengembalian like '"+idp+"'";
            PreparedStatement gidc = sql_connect.sqlConnect.prepareStatement(sql);
            ResultSet rs = gidc.executeQuery();
            if(rs.next())
            {
                try
                {
                    String save = "delete from pengembalian where id_pengembalian='"+idr+"'";
                    PreparedStatement sv = sql_connect.sqlConnect.prepareStatement(save);
                    sv.executeUpdate();

                    JOptionPane.showMessageDialog(rootPane, "Data has been delete");
                    this.hide();
                }
                catch (Exception a)
                {
                    JOptionPane.showMessageDialog(rootPane, "Data failed to delete");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Please enter valid ID Return");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            this.hide();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try
        {
            sql_connect.Koneksi();
            String idp = jTextField1.getText();
            String sql = "SELECT * FROM pengembalian WHERE id_pengembalian like '"+idp+"'";
            PreparedStatement dt = sql_connect.sqlConnect.prepareStatement(sql);
            ResultSet rs = dt.executeQuery();
            if(rs.next())
            {
                jTextField12.setText(rs.getString("id_pengembalian"));
                jTextField18.setText(rs.getString("id_transaksi"));
                SimpleDateFormat sdf;
                sdf = new SimpleDateFormat("dd-MM-yyyy");
                jDateChooser2.setDate(sdf.parse(rs.getString("tgl_pengembalian")));
                jTextField14.setText(rs.getString("denda"));
                jComboBox5.setSelectedItem(rs.getString("kondisi_sepeda"));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Not Found");
                jTextField1.requestFocus();
            }
         }
         catch(Exception ex)
         {
             JOptionPane.showMessageDialog(null, ex);
         }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }
    
    //EDIT FRAME
    public void Frame(javax.swing.JFrame objFrame){
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY); 
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("data/sepeda.png")));
    }
    
    public void isi()
    {
        jTextField12.setText(AutoID.Return());
        Calendar d = Calendar.getInstance();
        d.add(Calendar.YEAR ,0);
        jDateChooser2.setCalendar(d);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField18;
    // End of variables declaration//GEN-END:variables
}
